name: cDDIM
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - ca-certificates
  - libffi
  - ncurses
  - openssl
  - readline
  - setuptools
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - pip:
    - contourpy
    - cycler
    - filelock
    - fonttools
    - fsspec
    - importlib-resources
    - jinja2
    - kiwisolver
    - markupsafe
    - matplotlib
    - mpmath
    - networkx
    - numpy
    - packaging
    - pillow
    - pyparsing
    - python-dateutil
    - scipy
    - six
    - sympy
    - torch
    - torchaudio
    - torchvision
    - tqdm
    - typing-extensions
    - zipp
